[2023-01-24T15:18:06.082+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exercise18.drop_table manual__2023-01-24T15:18:03.916258+00:00 [queued]>
[2023-01-24T15:18:06.100+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exercise18.drop_table manual__2023-01-24T15:18:03.916258+00:00 [queued]>
[2023-01-24T15:18:06.100+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T15:18:06.101+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-24T15:18:06.101+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T15:18:06.131+0000] {taskinstance.py:1304} INFO - Executing <Task(SqliteOperator): drop_table> on 2023-01-24 15:18:03.916258+00:00
[2023-01-24T15:18:06.140+0000] {standard_task_runner.py:55} INFO - Started process 123 to run task
[2023-01-24T15:18:06.147+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exercise18', 'drop_table', 'manual__2023-01-24T15:18:03.916258+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/exercise18.py', '--cfg-path', '/tmp/tmpj_9yasvd']
[2023-01-24T15:18:06.151+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask drop_table
[2023-01-24T15:18:06.259+0000] {task_command.py:389} INFO - Running <TaskInstance: exercise18.drop_table manual__2023-01-24T15:18:03.916258+00:00 [running]> on host 3eb38391a0f6
[2023-01-24T15:18:06.319+0000] {abstractoperator.py:596} ERROR - Exception rendering Jinja template for task 'drop_table', field 'sql'. Template: 'sql/drop_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-01-24T15:18:06.321+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1497, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2119, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1196, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-01-24T15:18:06.339+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=exercise18, task_id=drop_table, execution_date=20230124T151803, start_date=20230124T151806, end_date=20230124T151806
[2023-01-24T15:18:06.359+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task drop_table (sql/drop_table.sql; 123)
[2023-01-24T15:18:06.400+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-24T15:18:06.460+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
